modLoader="javafml"
loaderVersion="[32,)"
license="MIT"

[[mods]]
modId="ezinventory"
version="1.0"
displayName="Easy Inventory"
issueTrackerURL=""
displayURL=""
logoFile=""
credits=""
authors="AreUThreateningMe"
description='''
Inventory Management
'''
[[dependencies.ezinventory]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ezinventory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.16.4]"
    ordering="AFTER"
    side="BOTH"
