modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"

[[mods]]
modId = "inventoryhotswap"
version = "1.3"
displayName = "Inventory Hotswap"
issueTrackerURL = "https://github.com/kregerl/hotswap/issues"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/inventory-hotswap"
logoFile = "inventoryHotswapLogo.png"
credits = ""
authors = "AreUThreateningMe"
description = '''
Quickly switch between items in your inventory.
'''
[[dependencies.inventoryhotswap]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.inventoryhotswap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "AFTER"
side = "BOTH"
