modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "inventoryhotswap"
version = "1.4"
displayName = "Inventory Hotswap"
issueTrackerURL = "https://github.com/kregerl/hotswap/issues"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/inventory-hotswap"
logoFile = "META-INF/inventoryHotswapLogo.png"
credits = ""
authors = "AreUThreateningMe"
description = '''
Quickly switch between items in your inventory.
'''
[[dependencies.inventoryhotswap]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.inventoryhotswap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "AFTER"
side = "BOTH"
