modLoader="javafml"
loaderVersion="[32,)"
license="MIT"

[[mods]]
modId="inventoryhotswap"
version="1.0"
displayName="Inventory Hotswap"
issueTrackerURL="https://github.com/kregerl/hotswap/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/inventory-hotswap"
logoFile="inventoryHotswapLogo.png"
credits=""
authors="AreUThreateningMe"
description='''
Quickly switch between items in your inventory.
'''
[[dependencies.inventoryhotswap]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.inventoryhotswap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.16.5]"
    ordering="AFTER"
    side="BOTH"
